title: Cagdas Yonder - Developer, Designer & Blogger
email: cagdasyonder@outlook.com
description: >
  Hello there, my name is Yonder. I am a developer, designer & blogger.
  Check out my last projects and designs.
url: "http://cagdasyonder.com"

# Build settings
markdown: kramdown
